// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pceldcylqpwrfkwbrlxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZWxkY3lscXB3cmZrd2JybHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDIzMDMsImV4cCI6MjA2NTU3ODMwM30.BIS3Up8tCRhQrm4asmloXqsdeHqfXlvzYZKt-a9Qss8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);